# Generated by Django 5.0.7 on 2024-11-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='purchased_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.ticket'),
            preserve_default=False,
        ),
    ]
