# Generated by Django 5.0.7 on 2024-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_perfomer_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfomer',
            name='security_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
