# Generated by Django 5.0.7 on 2024-11-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
