# Generated by Django 5.0.7 on 2024-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_perfomer_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite_performer_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
