# Generated by Django 5.0.7 on 2024-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_invitation_duration_invitation_invite_performer_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('minutes', 'Minutes')], default='hours', max_length=10, null=True),
        ),
    ]
