# Generated by Django 5.0.7 on 2024-11-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_invitation_duration_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=9999999999999999, null=True),
        ),
    ]
