# Generated by Django 5.0.7 on 2024-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomer',
            name='video_highlight',
            field=models.URLField(blank=True, null=True),
        ),
    ]
