# Generated by Django 5.0.7 on 2024-11-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_perfomer_video_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='base.perfomer')),
            ],
        ),
    ]
