# Generated by Django 5.0.7 on 2024-11-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_parkinglot_parkingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingbooking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parkingbooking',
            name='qr_code',
            field=models.ImageField(editable=False, null=True, unique=True, upload_to='parking_qr_codes/'),
        ),
    ]
