# Generated by Django 5.0.7 on 2024-11-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_parkingbooking_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingbooking',
            name='booking_id',
        ),
    ]
