# Generated by Django 5.0.7 on 2024-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_parkingbooking_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingbooking',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='parking_qr_codes/'),
        ),
    ]
